version: 2
updates:
  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security

  - package-ecosystem: npm
    directory: /tooling/node
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security

  - package-ecosystem: pip
    directory: /tooling/python
    schedule:
      interval: weekly
    labels:
      - dependencies
      - security
